conda/environments/pipelines-ide.yml
doc/UsingPipelines.rst

Docs need a general revision, but adding this here: https://github.com/CGATOxford/CGATPipelines/pull/403

Clarify expected fastq name for input files

---

CGATPipelines/pipeline_template_data/pipeline_template_full.py
CGATPipelines/pipeline_template_data/pipeline_template_minimal.py

Surely it needs more updating, adding the changes in https://github.com/CGATOxford/CGATPipelines/pull/405 here

Update pipeline template

---

CGATPipelines/PipelineBamStats.py
CGATPipelines/pipeline_bamstats.py
CGATPipelines/pipeline_bamstats/pipeline.ini
CGATPipelines/pipeline_bamstats/pipeline.yml

@Acribbs I am not updating the notebooks so pdf reports will be created (see https://github.com/CGATOxford/CGATPipelines/pull/404 )
Please let me know if it is ok to merge

migrating https://github.com/CGATOxford/CGATPipelines/pull/404

---

CGATPipelines/pipeline_exome.py
CGATPipelines/pipeline_exome/pipeline.ini
CGATPipelines/pipeline_exome/pipeline.yml

Migrating https://github.com/CGATOxford/CGATPipelines/pull/417

Update annotateVariantsSNPeff in pipeline_exome

---

CGATPipelines/pipeline_mapping.py

migrating  https://github.com/CGATOxford/CGATPipelines/pull/420

Update loadReadCounts in pipeline_mapping to avoid duplicating entries

---

CGATPipelines/PipelinePreprocess.py

migrating https://github.com/CGATOxford/CGATPipelines/pull/423

fix cutadapt paired untrimmed command

---

CGATPipelines/pipeline_readqc/pipeline.ini
CGATPipelines/pipeline_readqc/pipeline.yml

migrating https://github.com/CGATOxford/CGATPipelines/pull/422

Disable fastq_screen in pipeline_readqc by default

---

CGATPipelines/PipelineGO.py
CGATPipelines/PipelineGeneset.py
CGATPipelines/PipelineGtfsubset.py
CGATPipelines/pipeline_genesets.py
CGATPipelines/pipeline_genesets/pipeline.ini
CGATPipelines/pipeline_genesets/pipeline.yml

migrating:
* https://github.com/CGATOxford/CGATPipelines/pull/402
* https://github.com/CGATOxford/CGATPipelines/pull/408

Update memory requirements in pipeline_genesets

---

CGATPipelines/PipelineRnaseq.py

Pipelines using `cgat-core` can now rely on `TMPDIR` being correctly set per job so it can be directly used to work with temporary folders. xref: https://github.com/cgat-developers/cgat-core/pull/30
ping @nickilott this PR is adding the changes commented in https://github.com/CGATOxford/CGATPipelines/pull/418 . I would be grateful if you could have a look. Would it be possible to run a test on your end to verify that it works as expected?

Update runFeatureCounts in PipelineRnaseq.py

---

CGATPipelines/PipelineRnaseq.py

@Acribbs are you able to test this?

bugfix runFeatureCounts in PipelineRnaseq.py

---

install-CGAT-tools.sh
scripts/conda.py
tests/test_import.py

* clean up environment before performing the installation
* pin installed packages in conda environments

Update installation 

---

install-CGAT-tools.sh
scripts/conda.py

Please see discussions in https://github.com/cgat-developers/cgat-core/issues/44 and https://github.com/cgat-developers/cgat-flow/issues/36

Do not purge user modules during installation and fix #36

---

cgatpipelines/tasks/peakcalling.py

Execute the predictd R script and save the PDF file before removing t…he temporary folder

{KR} use the predict R script before deleting it

---

cgatpipelines/tools/pipeline_docs/pipeline_peakcalling/notebooks/template_peakcalling_filtering_Report.ipynb

I'm running into this error: http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

IX Indexer is Deprecated (pandas)

---

cgatpipelines/tasks/peakcalling.py
cgatpipelines/tools/pipeline_peakcalling.py
cgatpipelines/tools/pipeline_peakcalling/pipeline.yml

I left a bunch of print statements related to debugging. I'll remove them if I get positive feedback about merging this PR to `master`

 Add peakcalling memory options to pipeline.yml

---

.travis.yml
conda/environments/cgat-flow-pipelines.yml
conda/environments/cgat-flow-tests.yml
conda/environments/cgat-flow.yml
conda/environments/pipeline-bamstats.yml
conda/environments/pipeline-enrichment.yml
conda/environments/pipeline-genesets.yml
conda/environments/pipeline-intervals.yml
conda/environments/pipeline-mapping.yml
conda/environments/pipeline-peakcalling-sicer.yml
conda/environments/pipeline-peakcalling.yml
conda/environments/pipeline-readqc.yml
conda/environments/pipeline-rnaseqde.yml
conda/environments/pipeline-rnaseqqc.yml
conda/environments/pipeline-scrnaseqqc.yml
conda/environments/pipeline-windows.yml
conda/environments/pipelines-extra.yml
conda/environments/pipelines-macs2.yml
conda/environments/pipelines-sailfish.yml
conda/environments/pipelines-salmon.yml
conda/environments/pipelines-splicing.yml
conda/environments/pipelines-tophat2.yml
install-devel.sh

Please do not merge. See discussions in https://github.com/cgat-developers/cgat-flow/issues/88

[WIP] Review conda install

---

.travis.yml
cgatpipelines/tools/pipeline_readqc.py
install-devel.sh

The `build_report` task does not exist (any more).

Update documentation of pipeline_readqc.py

---

cgatpipelines/tasks/expression.py

rpy2 library migration fix

---

install-devel.sh

Jenkins tests are currently failing for cgat-flow due to an issue with the testing part of the install-devel.sh script. This PR is trying to fix that.

Update install-devel.sh to fix Jenkins issue

---

conda/environments/cgat-flow-pipelines.yml
conda/environments/cgat-flow-tests.yml
conda/environments/pipeline-bamstats.yml
conda/environments/pipeline-genesets.yml
conda/environments/pipeline-intervals.yml
conda/environments/pipeline-peakcalling.yml

Pin pysam to 0.15.2
